### PR TITLE
ballle98/AqualinkD#17: Status sync into ha-bridge

### PR DESCRIPTION
**Pull request by ballle98**
added feature to sync changes to ha-bridge since ha-bridge will not process MQTT

### CODE REVIEW

**Comment by ballle98** [comment]
rebased to version 1.3.4a

**Comment by ballle98** [comment]
@sfeakes rebased this pull request to 2.2.2a

**Comment by ballle98** [comment]
fixes #122

**Comment by sfeakes** [comment]
This at a minimum needs to be compile time option. But also question if AqualinkD is even the right place to put this at all. Seems there are better options out there that support MQTT for this type of thing. What makes ha-bridge the best option for Alexa integration?

**Comment by ballle98** [comment]
I looked into the MQTT option first but ha-bridge does not support status updates from MQTT and it adds complexity since ha-bridge can use the aqualinkd API directly without MQTT.  My goal was to control the pool with Alexa so I didn't need MQTT.  I could definitely see making it more generic so that it calls a shell script and the user puts whatever they want in the shell script. 

Is there significant benefit from putting it in a compile option?  Is there concern over the binary size of aqualinkd?  If the ha-bridge is not set it's a fast run time check, there is minimal impact on execution time.  It could be consolidated with the MQTT check and there would be no impact on execution time.  The one drawback I see to the different compile options is they need to be validated and you create permutations of test and potentially fragment your user base.

**Comment by niharmehta** [comment]
It would be terrific to have HA-Bridge integration with AqualinkD.  Been using it for years to integrate  my vera HA system, and it has been rock solid stable and extremely easy to configure. Likely if others are asking for Alexa integration, this is likely the most turn-key method of making it work without a full blown HA system.

**Pull request closed without merging**
